unbind C-b
set -g prefix C-x
bind C-x send-prefix
set -g history-limit 102400
setw -g mode-keys vi
set -g escape-time 10

bind \\ split-window -h
bind - split-window -v
unbind '"'
unbind %

bind r source-file ~/.tmux.conf

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

set -g mouse on

unbind-key -T copy-mode-vi v

bind-key -T copy-mode-vi v \
  send-keys -X begin-selection

bind-key -T copy-mode-vi 'C-v' \
  send-keys -X rectangle-toggle

bind-key -T copy-mode-vi y \
  send-keys -X copy-pipe-and-cancel "pbcopy"

bind-key -T copy-mode-vi MouseDragEnd1Pane \
  send-keys -X copy-pipe-and-cancel "pbcopy"

bind c new-window -c '#{pane_current_path}'

# Vague.nvim Palette
thm_bg="#141415"
thm_fg="#cdcdcd"
thm_line="#252530"
thm_comment="#606079"
thm_blue="#6e94b2"
thm_red="#c48282"
thm_orange="#e8b589"

# Bar Settings
set -g status-position bottom
set -g status-justify left
set -g status-style "bg=${thm_bg} fg=${thm_fg}"
set -g status-left-length "100"
set -g status-right-length "100"

# Borders
set -g pane-border-style "fg=${thm_line}"
set -g pane-active-border-style "fg=${thm_blue}"

# Message / Command
set -g message-style "fg=${thm_blue},bg=${thm_line},align=centre"
set -g message-command-style "fg=${thm_blue},bg=${thm_line},align=centre"

# Windows
setw -g window-status-separator ""
setw -g window-status-format "#[fg=${thm_comment},bg=${thm_bg}] #I #W "
setw -g window-status-current-format "#[bg=${thm_line},fg=${thm_blue},bold] #I #W "

# Status Left (Session Name)
set -g status-left "#[bg=${thm_blue},fg=${thm_bg},bold] #S "

# Status Right (Prefix Indicator + Time)
set -g status-right "#{?client_prefix,#[bg=${thm_red} fg=${thm_bg} bold] PREFIX ,#[fg=${thm_comment}]} #[fg=${thm_fg},bg=${thm_line}] %H:%M "
